[build]
  command = "cd client && npm install && npm run build"
  publish = "client/build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[env]
  REACT_APP_SERVER_DOMAIN = "https://doctorappointment-m5j2.onrender.com/api"
